---
title: "Introduction to the Package"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to the Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This is an overview of the main functions in the packages. There are also several helper functions, but since they are not intended to be used directly, they are not covered here.

## Package Purpose

The package is designed to provide to tools to analysis and visualize data regarding auto accidents in the United States based on year.  It assumes the data is stored in .csv.bz2 files in the packages exdata folder.  THe data can be downloaded from [here](https://d18ky98rnyall9.cloudfront.net/_e1adac2a5f05192dc8780f3944feec13_fars_data.zip?Expires=1481068800&Signature=ZqNhKJz1-u0PZ7-AQsd0QB-ZClMMfDEIheh8J7nMB-zjJ5Jrzpt91cVWBFFv~~Rg2QF89dU~6KX0j~BEtW6nXT47C7~TlTindl13M00clEO8bVn3t49d974paqq-NORDqVIGFFgHIkz0I1P0ER4LzPV49pj7BSJxCVVP~jybO54_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A).

Data files for 2013, 20414, and 2015 has been included with the package.

## Main Functions
The first user-facing function is fars_summarize_years, which takes a vector of years and returns a tibblefor each year. Each tibble contains the total munber of accidents in each month.

The other function available to the user is fars_map_state.  This takes a state code and a single year and returns a map of the state with all the accidents from that year plotted on the map.  A key for state codes is available [url](url).
